[assembly: System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("DynamicProxyGenAssembly2")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Clarity.Core.Data.Fakes")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Clarity.Core.Data.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Clarity.Core.Requests.Fakes")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Clarity.Core.RequestHandlers.Fakes")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Clarity.Core.RequestHandlers.Tests")]
